web_ui/web_ui_project/im1/urls.py
from django.conf.urls import url

from . import views

app_name = 'im1'
urlpatterns = [
    # ex: /im1/
    url(r'^$', views.index, name='index'),
    url(r'^json/$', views.json_response, name='json'),
    # url(r'^observed/$', views.observed, name='observed'),
    url(r'^post_data/$', views.post_data, name='post_data'),
]

web_ui/web_ui_project/im2/urls.py
from django.conf.urls import url

from . import views

app_name = 'im2'
urlpatterns = [
    # ex: /im1/
    url(r'^$', views.index, name='index'),
    url(r'^post_data/$', views.post_data, name='post_data'),
]

web_ui/web_ui_project/web_ui_project/urls.py
from django.conf.urls import include, url
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^im1/', include('im1.urls')),
    url(r'^im2/', include('im2.urls')),
    url(r'^csv1/', include('csv1.urls')),
    url(r'^gdrive1/', include('gdrive1.urls')),
    url(r'^log_visual/', include('log_visual.urls')),
]

web_ui/web_ui_project/im2/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

web_ui/web_ui_project/im2/views.py
import json
# import urllib2

# from django.http import HttpResponse
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.template import loader

from web_ui_project.project_settings import app_list
from im.get_imGate import get_wave_data, get_appliance_map, get_appliance_name, get_appliance_type

# logging
import logging

default_values = {
    'data_type': "data",
    'customer': "0039_9000000002",
    # 'sts': 1465850300,
    'sts': 1465763880,
    'ets': 1465850360,
    'time_unit': [20],
}
previous_values = default_values.copy()

time_unit_data = {
    'name': "time_unit",
    'choice_list':
        [
            {'value': 10, 'text': "Second", 'ch': ""},
            {'value': 20, 'text': "Minute", 'ch': "checked"},
            {'value': 25, 'text': "30 Minutes", 'ch': ""},
            {'value': 30, 'text': "Hour", 'ch': ""},
            {'value': 40, 'text': "Day", 'ch': ""},
            {'value': 50, 'text': "Month", 'ch': ""},
            {'value': 60, 'text': "Year", 'ch': ""},
        ]
}

time_unit_map = {}
for choice in time_unit_data['choice_list']:
    time_unit_map[choice['value']] = choice['text']

logger = logging.getLogger('web_ui.im')


def index(request):
    appliance_map_dump = json.dumps(get_appliance_map())
    time_map_dump = json.dumps(time_unit_map)
    context = {
        'app_list': app_list,
        'populate_values': default_values,
        'time_unit': time_unit_data,
        'time_map_str': time_map_dump,
        'app_map_str': appliance_map_dump,
    }
    return render(request, 'im2/index.html', context)


def post_data(request):
    parse_request = request.POST
    if "calculate" in parse_request["data_type"]:
        dict_data = calculate_matching(parse_request)
        return JsonResponse(dict_data)
    else:
        wave_data = wave_data_request(parse_request)
        appliance_list = wave_data['estimated_data'][u'data'][0][u'appliance_types']
        seen = set()
        unique_appliance_list = [app for app in appliance_list if
                                 app[u'appliance_type_id'] not in seen and not seen.add(app[u'appliance_type_id'])]
        html = """"""
        graph_count = len(unique_appliance_list)
        for appliance_index, appliance in enumerate(unique_appliance_list):
            c = {
                'graph_id': "graph" + str(appliance_index),
                'graph_num': "Num" + str(appliance_index),
                'graph_title': "{}, {}:{}".format(get_appliance_name(appliance[u'appliance_type_id']),
                                                  appliance[u'appliance_type_id'],
                                                  get_appliance_type(appliance[u'appliance_type_id'])),
            }
            html += loader.render_to_string('im2/graph.html', context=c)
        dict_data = {
            'wave_data': wave_data,
            'headers': previous_values,
            'graph_html': html,
            'graph_count': graph_count,
        }
        return JsonResponse(dict_data)


def wave_data_request(settings):
    for key, item in settings.iterlists():
        if key in previous_values:
            if isinstance(previous_values[key], list):
                previous_values[key] = item
            elif len(item) == 1:
                previous_values[key] = item[0]
            else:
                raise Exception("parse_request:error1:{}".format(len(item)))
    try:
        return {
            'observed_data': get_json(data_type='observed_data'),
            'estimated_data': get_json(data_type='estimated_data')
        }
    except IOError as e:
        logger.warning("im2.parse_request: %s", e)
        return {'error': "{!r}".format(e if not e.args else e.args[0])}
    except ValueError as e:
        logger.warning("im2.parse_request: %s", e)
        return {'error': "{!r}".format(e if not e.args else e.args[0])}


def calculate_matching(post_request):

    # To do the calculation here
    # post_request is the query dict containing the posted data from client
    temp_values = {'calculation': True, 'f_measure': 1, 'matching_rate': 0.5}
    return temp_values


def get_json(data_type=None,
             customer=None,
             sts=None,
             ets=None,
             time_units=None):
    # This is necessary for some reason, if assigned directly it doesn't update and only a list of length 1 is retrieved
    data_type = data_type or previous_values['data_type']
    customer = customer or previous_values['customer']
    sts = sts or previous_values['sts']
    ets = ets or previous_values['ets']
    time_units = time_units or previous_values['time_unit']
    wave_data = get_wave_data(data_type, customer, sts, ets, time_units)
    return wave_data


# def main():
#     # estimated_data = get_json(data_type='estimated_data')
#     # observed_data = get_json(data_type='observed_data')
#     # print get_appliance_id_map()
#     pass
#
# if __name__ == "__main__":
#     main()

web_ui/web_ui_project/im2/templates/im2/graph.html
<div class="panel panel-default graph-populate-panel">
    <div class="panel-heading" data-toggle="collapse" href="#collapse{{ graph_num }}" aria-expanded="true" aria-controls="collapse{{ graph_num }}">
        <h4 class="panel-title" role="tab" id="heading{{ graph_num }}">
            <a role="button">
                {{ graph_title }}
            </a>
        </h4>
    </div>
    <div id="collapse{{ graph_num }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ graph_num }}">
        <div class="panel-body">
            <div id="{{ graph_id }}" class="graph-div"></div>
        </div>
    </div>
</div>

web_ui/web_ui_project/im2/templates/im2/index.html
<!DOCTYPE html>
<html lang="en">

{% include "web_ui/header.html" with app_name='im2' %}

<body>

    {% include "web_ui/nav_bar.html" with app_name='im2' %}

    <div class="container">
        <h2 class="text-center">imGate API</h2>
        <div class="row rounded-box">
            <form role="form" id="im_form1" class="graph_form" action="" method="post" target="_blank"> {% csrf_token %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="row">
                                <div class="col-md-4 form-group">
                                    <label for="customer_id">Customer ID:</label>
                                    <input type="text" name="customer" value="{{ populate_values.customer }}" class="form-control" id="customer_id" placeholder="Email">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label for="sts">Start timestamp:</label>
                                    <input type="text" name="sts" value="{{ populate_values.sts }}" class="form-control ts" id="sts" placeholder="Start Timestamp">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label for="ets">End timestamp:</label>
                                    <input type="text" name="ets" value="{{ populate_values.ets }}" class="form-control ts" id="ets" placeholder="End Timestamp">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="col-md-4 form-group">
                                    <label for="sts">Start date time:</label>
                                    <div class='input-group date dtpicker' id='sdtpicker'>
                                        <input type="text" class="form-control" id="sdt" placeholder="Start Date Time">
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-md-4 form-group">
                                    <label for="sts">End date time:</label>
                                    <div class='input-group date dtpicker' id='edtpicker'>
                                        <input type="text" class="form-control" id="edt" placeholder="End Date Time">
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 form-group">
                            <label>Time Units:</label>
                            <div style="height: 107.8px" class="form-control pre-scrollable">
                                {% for choice in time_unit.choice_list %}
                                    <div class="checkbox">
                                        <label class="checkbox"><input type="checkbox" name="{{ time_unit.name }}" value="{{ choice.value }}" {{ choice.ch }}> {{ choice.text }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-3 form-group">
                            <button class="fetch btn btn-primary" name="data_type" value="data" type="submit">Get Data</button>
                        </div>
                        <div class="col-md-3 form-group">
                            <button class="fetch btn btn-primary" name="calculate" value="calculate" type="submit">Matching data</button>
                        </div>
                        <div class="col-md-3 form-group">
                            <button class="fetch cancel btn btn-default" type="button" tabindex="-1">Cancel</button>
                        </div>

                    </div>
                </div>
            </form>
        </div>

        <div class="row rounded-box">
            <div>
                <table class="table table-bordered">
                    <tr>
                        <th>Data</th>
                        <th>Customer ID<br></th>
                        <th>Start Timestamp<br></th>
                        <th>End Timestamp<br></th>
                        <th>Time Units<br></th>
                    </tr>
                    <tr>
                        <td id="get_data"></td>
                        <td id="get_cust"></td>
                        <td id="get_sts"></td>
                        <td id="get_ets"></td>
                        <td id="get_time"></td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="row rounded-box">
            <div>
                <table class="table table-bordered">
                    <tr>
                        <th>F Measure</th>
                        <th>Matching Rate</th>
                    </tr>
                    <tr>
                        <td id="get_f_measure"></td>
                        <td id="get_matching_rate"></td>
                    </tr>
                </table>
            </div>
        </div>

    </div>
    <h3 id="data-heading" class="text-center">imGate data</h3>

    <div id="graph-container" class="graph-sync graph-populate">
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" href="#collapseAggregate" aria-expanded="true" aria-controls="collapseAggregate">
                <h4 class="panel-title" role="tab" id="headingAggregate">
                    <a role="button">
                        Aggregate Data
                    </a>
                </h4>
            </div>
            <div id="collapseAggregate" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingAggregate">
                <div class="panel-body">
                    <div id="graphAggregate" class="graph-div"></div>
                </div>
            </div>
        </div>
    </div>

</body>

<script>
    django_populate_values_data_type = "{{ populate_values.data_type }}"
    django_time_map_string = '{{ time_map_str|safe }}';
    django_app_map_string = '{{ app_map_str|safe }}';
    django_post_url = "{% url 'im2:post_data' %}";
</script>

{% include "web_ui/footer.html" %}

{% load static %}
<script src="{% static 'im2/im2_graph.js' %}"></script>

</html>