web_ui/web_ui_project/im1/urls.py
from django.conf.urls import url

from . import views

app_name = 'im1'
urlpatterns = [
    # ex: /im1/
    url(r'^$', views.index, name='index'),
    url(r'^json/$', views.json_response, name='json'),
    # url(r'^observed/$', views.observed, name='observed'),
    url(r'^post_data/$', views.post_data, name='post_data'),
]

web_ui/web_ui_project/web_ui_project/urls.py
from django.conf.urls import include, url
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^im1/', include('im1.urls')),
    url(r'^im2/', include('im2.urls')),
    url(r'^csv1/', include('csv1.urls')),
    url(r'^gdrive1/', include('gdrive1.urls')),
    url(r'^log_visual/', include('log_visual.urls')),
]

web_ui/web_ui_project/im1/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

web_ui/web_ui_project/im1/views.py
import json
# import urllib2

from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render

from web_ui_project.project_settings import app_list
from im.get_imGate import get_wave_data, get_appliance_map

# logging
import logging

time_unit_data = {
    'name': "time_unit",
    'choice_list':
        [
            {'value': 10, 'text': "Second", 'ch': ""},
            {'value': 20, 'text': "Minute", 'ch': "checked"},
            {'value': 25, 'text': "30 Minutes", 'ch': ""},
            {'value': 30, 'text': "Hour", 'ch': ""},
            {'value': 40, 'text': "Day", 'ch': ""},
            {'value': 50, 'text': "Month", 'ch': ""},
            {'value': 60, 'text': "Year", 'ch': ""},
        ]
    }

default_values = {
    'data_type': "observed_data",
    'customer': "0039_9000000002",
    # 'sts': 1465850300,
    'sts': 1465763880,
    'ets': 1465850360,
    'time_unit': [20],
    }

time_unit_map = {
    10: "Second",
    20: "Minute",
    25: "30 Minutes",
    30: "Hour",
    40: "Day",
    50: "Month",
    60: "Year",
}

previous_values = default_values.copy()

logger = logging.getLogger('web_ui.im')


def index(request):
    appliance_map_dump = json.dumps(get_appliance_map())
    time_map_dump = json.dumps(time_unit_map)
    context = {
        'app_list': app_list,
        'populate_values': default_values,
        'time_unit': time_unit_data,
        'time_map_str': time_map_dump,
        'app_map_str': appliance_map_dump,
    }
    return render(request, 'im1/index.html', context)


def post_data(request):
    json_data = {'wave_data': parse_request(request),
                 'headers': previous_values}
    data = json.dumps(json_data)
    return HttpResponse(data)


def json_response(request):
    return JsonResponse(parse_request(request))


def parse_request(request):
    settings = request.POST

    for key, item in settings.iterlists():
        if key in previous_values:
            if isinstance(previous_values[key], list):
                # previous_values[key] = settings.getlist(key)
                previous_values[key] = item
            elif len(item) == 1:
                previous_values[key] = item[0]
            else:
                raise Exception("parse_request:error1:{}".format(len(item)))
    try:
        return get_json()
    except IOError as e:
        logger.warning("im1.parse_request: %s", e)
        return {'error': "{!r}".format(e if not e.args else e.args[0])}
    except ValueError as e:
        logger.warning("im1.parse_request: %s", e)
        return {'error': "{!r}".format(e if not e.args else e.args[0])}


def get_json(data_type=None,
             customer=None,
             sts=None,
             ets=None,
             time_units=None):
    # This is necessary for some reason, if assigned directly it doesn't update and only a list of length 1 is retrieved
    data_type = data_type or previous_values['data_type']
    customer = customer or previous_values['customer']
    sts = sts or previous_values['sts']
    ets = ets or previous_values['ets']
    time_units = time_units or previous_values['time_unit']
    wave_data = get_wave_data(data_type, customer, sts, ets, time_units)
    return wave_data


# def main():
#     pass
#
# if __name__ == "__main__":
#     main()

web_ui/web_ui_project/im1/templates/im1/index.html
<!DOCTYPE html>
<html lang="en">

{% include "web_ui/header.html" with app_name='im1' %}

<body>

    {% include "web_ui/nav_bar.html" with app_name='im1' %}

    <div class="container">
        <h2 class="text-center">imGate API</h2>
        <div class="row rounded-box">
            <form role="form" class="graph_form" action="{% url 'im1:json' %}" method="post" target="_blank"> {% csrf_token %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="row">
                                <div class="col-md-4 form-group">
                                    <label for="customer_id">Customer ID:</label>
                                    <input type="text" name="customer" value="{{ populate_values.customer }}" class="form-control" id="customer_id" placeholder="Email">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label for="sts">Start timestamp:</label>
                                    <input type="text" name="sts" value="{{ populate_values.sts }}" class="form-control ts" id="sts" placeholder="Start Timestamp">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label for="ets">End timestamp:</label>
                                    <input type="text" name="ets" value="{{ populate_values.ets }}" class="form-control ts" id="ets" placeholder="End Timestamp">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="col-md-4 form-group">
                                    <label for="sts">Start date time:</label>
                                    <div class='input-group date dtpicker' id='sdtpicker'>
                                        <input type="text" class="form-control" id="sdt" placeholder="Start Date Time">
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-md-4 form-group">
                                    <label for="sts">End date time:</label>
                                    <div class='input-group date dtpicker' id='edtpicker'>
                                        <input type="text" class="form-control" id="edt" placeholder="End Date Time">
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 form-group">
                            <label>Time Units:</label>
                            <div style="height: 107.8px" class="form-control pre-scrollable">
                                {% for choice in time_unit.choice_list %}
                                    <div class="checkbox">
                                        <label class="checkbox"><input type="checkbox" name="{{ time_unit.name }}" value="{{ choice.value }}" {{ choice.ch }}> {{ choice.text }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 form-group">
                            <button class="fetch btn btn-primary" name="data_type" value="observed_data" type="submit">Show Observed Data</button>
                        </div>
                        <div class="col-md-3 form-group">
                            <button class="fetch btn btn-primary" name="data_type" value="estimated_data" type="submit">Show Estimated Data</button>
                        </div>
                        <div class="col-md-3 form-group">
                            <button class="fetch cancel btn btn-default" type="button" tabindex="-1">Cancel</button>
                        </div>
                        <div class="col-md-3 form-group">
                            <button class="btn btn-link" value="json" type="submit" tabindex="-1">Show JSON</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="row rounded-box">
            <div>
                <table class="table table-bordered">
                    <tr>
                        <th>Data</th>
                        <th>Customer ID<br></th>
                        <th>Start Timestamp<br></th>
                        <th>End Timestamp<br></th>
                        <th>Time Units<br></th>
                    </tr>
                    <tr>
                        <td id="get_data"></td>
                        <td id="get_cust"></td>
                        <td id="get_sts"></td>
                        <td id="get_ets"></td>
                        <td id="get_time"></td>
                    </tr>
                </table>
            </div>
        </div>

    </div>
    <h3 id="data-heading" class="text-center">imGate data</h3>

    <div id="graph-container" class="graph-sync">
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <h4 class="panel-title" role="tab" id="headingOne">
                    <a role="button">
                        Aggregate Data
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <div id="graph1" class="graph-div"></div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <h4 class="panel-title" role="tab" id="headingTwo">
                    <a class="collapsed" role="button">
                        Appliance Data
                    </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">
                    <div id="graph2" class="graph-div"></div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                <h4 class="panel-title" role="tab" id="headingThree">
                    <a class="collapsed" role="button">
                        Stacked Data
                    </a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body">
                    <div id="graph3" class="graph-div"></div>
                </div>
            </div>
        </div>
    </div>

</body>

<script>
    django_populate_values_data_type = "{{ populate_values.data_type }}"
    django_time_map_string = '{{ time_map_str|safe }}';
    django_app_map_string = '{{ app_map_str|safe }}';
    django_post_url = "{% url 'im1:post_data' %}";
</script>

{% include "web_ui/footer.html" %}

{% load static %}
<script src="{% static 'im1/im1_graph.js' %}"></script>

</html>