detector/detector/detector/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('detector_view.urls')),
]

detector/detector/detector_view/urls.py
from django.conf.urls import url

import views

app_name = 'detector_view'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post_data/$', views.post_data, name='post_data')
]

detector/detector/detector_view/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

detector/detector/detector_view/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
import os
# Create your views here.


def index(request):
    return render(request, 'detector_view/detector.html')


def post_data(request):
    post_request = request.POST
    try:
        if post_request["ts"]:
            wave_data = get_data(waveforms=True)
            data = get_waveforms(wave_data, int(post_request["ts"]))
    except KeyError:
        data = get_data()
        scale_estimated(data)
    except:
        raise
    return return_json_response(data)


def scale_estimated(data, scale=1000):
    data["data"]["estimated"] = [est * scale for est in data["data"]["estimated"]]
    return data


def return_json_response(data):
    json_data = json.dumps(data)
    return HttpResponse(json_data)


def get_waveforms(data, ts):
    half_interval = 5
    return_data = {
        "timestamps": [],
        "data":
        {
         "waveforms": [],
         "diff": []
        }
    }
    position = data["timestamps"].index(ts)
    for count, position in enumerate(range(position - half_interval, position + half_interval)):
        return_data["timestamps"].append(data["timestamps"][position])
        return_data["data"]["waveforms"].append([])
        return_data["data"]["diff"].append([])
        for wave_count in range(64):
            return_data["data"]["waveforms"][count].append(data["data"]["waveforms"][position][wave_count])
            return_data["data"]["diff"][count].append(data["data"]["diff"][position][wave_count])

    return return_data


def get_data(waveforms=False):
    cdir = os.path.abspath(os.path.dirname(__file__))
    if waveforms:
        file_directory = os.path.join(cdir, 'waveforms.json')
    else:
        file_directory = os.path.join(cdir, 'power.json')
    f = open(file_directory, 'r')
    json_data = f.read()
    data = json.loads(json_data)
    f.close()
    return data

detector/detector/detector_view/templates/detector_view/detector.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detector</title>
</head>
<body>
    <h3 class="text-center">Detector setting</h3>
    <div id="graph-container" class="graph-sync">
        <div class="panel panel-default">
            <h4 class="panel-heading"> Power consumption</h4>
        </div>
        <div class="panel-body">
            <div id="graph_power" class="graph-div graph-loading"></div>
        </div>
        <div class="panel panel-default">
            <h4 class="panel-heading">Prediction probability</h4>
        </div>
        <div class="panel-body">
            <div id="graph_prediction" class="graph-div graph-loading"></div>
        </div>
        <div class = "row">
            <div class="col-md-6">
                <div class = "panel panel-default">
                    <h4 class="panel-heading">Waveforms</h4>
                </div>
                <div class="panel-body">
                    <div id="graph_waveforms" class="graph-div graph-loading"></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class = "panel panel-default">
                    <h4 class = "panel-heading">Diff Waveforms</h4>
                </div>
                <div class = "panel-body">
                    <div id = "graph_diff" class = "graph-div graph-loading"></div>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
    django_post_url = "{% url 'detector_view:post_data' %}";
    threshold_value = 0.6;
</script>

{% include "detector_view/footer.html" %}

{% load static %}
<script src="{% static 'detector/detector_graph.js' %}"></script>

</html>

detector/detector/detector_view/templates/detector_view/footer.html
{% load static %}

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>



<!-- Latest compiled and minified JavaScript -->


<script src="{% static 'detector/shared_utils.js' %}"></script>
<script src="{% static 'detector/shared_graph_utils.js' %}"></script>
<script src="{% static 'detector/shared_graph_settings.js' %}"></script>



<link rel="stylesheet" type="text/css" href="{% static 'detector/style.css' %}"/>